atico_spreadsheet_translator:
    frontend:
        provider:
            name: 'one_drive'
            source_resource: 'https://onedrive.live.com/embed?resid=AF6B7F4DC4426D56!114&authkey=%21AOntrGclPCi6zdA&em=2&cid=af6b7f4dc4426d56'
           # source_resource: 'https://onedrive.live.com/embed?cid=F52C4DBF73226B55&resid=F52C4DBF73226B55%21332&authkey=AEC-6FbEY7WAwgc&em=2'
        exporter:
            format: 'xliff'
            prefix: 'demo_'
            destination_folder: '%kernel.project_dir%/app/Resources/translations'
        shared:
            temp_local_source_file: '%kernel.project_dir%/downloaded_resource.xls'
            default_locale: 'en'
            name_separator: '#'